name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "::add-path::$HOME/.bun/bin"
        bun --version

    - name: Install dependencies
      run: bun install

    - name: Run tests
      run: bun test

    - name: Build project
      run: bun build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "::add-path::$HOME/.bun/bin"
        bun --version

    - name: Deploy to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 sync build/ s3://your-bucket-name
